name: Deploy To Server
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: actions/setup-node@v1
    - name: Login to Docker Hub
      run: docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
    - name: pushing to DockerHub
      run: |
        docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
        docker build . --file Dockerfile -t ismayil10/mohammedismayil.github.io
        docker push ismayil10/mohammedismayil.github.io
    - name: Configure SSH
      run: |
          git config --global user.email "mohammedismayil10@gmail.com"
          git config --global user.name "mohammedismayil"
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName "${{ secrets.SSH_HOST }}"
            User "${{ secrets.SSH_USER }}"
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
    - name: Pulling and run from DockerHub
      run: |
         ssh staging 'docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"'
         ssh staging 'docker pull ismayil10/mohammedismayil.github.io'
         ssh staging 'docker stop githubportfolio || true && docker rm githubportfolio || true'
         ssh staging 'docker run -e REACT_APP_GITHUB_TOKEN="${{ secrets.REACT_APP_GITHUB_TOKEN}}" -i -p 4000:4000 --name githubportfolio -d ismayil10/mohammedismayil.github.io'
